package com.hm.achievement.advancement;

/**
 * Class representing an advancement generated by Advanced Achievements.
 * 
 * @author Pyves
 *
 */
public class AchievementAdvancement {

	public static final String CRITERIA_NAME = "aach_handled";

	private String iconItem;
	private String iconData;
	private String title;
	private String description;
	private String parent;
	private String frame;

	private AchievementAdvancement(String iconItem, String iconData, String title, String description, String parent,
			String frame) {
		this.iconItem = iconItem;
		this.iconData = iconData;
		this.title = title;
		this.description = description;
		this.parent = parent;
		this.frame = frame;
	}

	public String toJson() {
		return "{\"criteria\": {\"" + CRITERIA_NAME + "\": {\"trigger\": \"minecraft:impossible\"}}, "
				+ "\"requirements\": [[\"" + CRITERIA_NAME + "\"]], " + "\"display\": " + "{\"icon\": {\"item\": \""
				+ iconItem + "\",\"data\": " + iconData + "}, " + "\"title\": \"" + title + "\", "
				+ "\"description\": \"" + description + "\", \"frame\": \"" + frame
				+ "\", \"announce_to_chat\": false}, \"parent\": \"advancedachievements:" + parent + "\"}";
	}

	public String toParentJson(boolean configHideAdvancements, String background) {
		if (configHideAdvancements) {
			return "{\"criteria\": {\"" + CRITERIA_NAME + "\": {\"trigger\": \"minecraft:impossible\"}}, "
					+ "\"requirements\": [[\"" + CRITERIA_NAME + "\"]], \"background\": \"" + background + "\"}";

		}
		return "{\"criteria\": {\"" + CRITERIA_NAME + "\": {\"trigger\": \"minecraft:impossible\"}}, "
				+ "\"requirements\": [[\"" + CRITERIA_NAME + "\"]], " + "\"display\": " + "{\"icon\": {\"item\": \""
				+ iconItem + "\",\"data\": " + iconData + "}, " + "\"title\": \"" + title + "\", "
				+ "\"description\": \"" + description + "\", \"frame\": \"" + frame
				+ "\", \"background\": \"" + background + "\", \"announce_to_chat\": false}}";
	}

	public static class AchievementAdvancementBuilder {

		private String iconItem;
		private String iconData;
		private String title;
		private String description;
		private String parent;

		public AchievementAdvancementBuilder iconItem(String iconItem) {
			this.iconItem = iconItem;
			return this;
		}

		public AchievementAdvancementBuilder iconData(String iconData) {
			this.iconData = iconData;
			return this;
		}

		public AchievementAdvancementBuilder title(String title) {
			this.title = title;
			return this;
		}

		public AchievementAdvancementBuilder description(String description) {
			this.description = description;
			return this;
		}

		public AchievementAdvancementBuilder parent(String parent) {
			this.parent = parent;
			return this;
		}

		public AchievementAdvancement buildTask() {
			return new AchievementAdvancement(iconItem, iconData, title, description, parent, "task");
		}

		public AchievementAdvancement buildChallenge() {
			return new AchievementAdvancement(iconItem, iconData, title, description, parent, "challenge");
		}

		public AchievementAdvancement buildGoal() {
			return new AchievementAdvancement(iconItem, iconData, title, description, parent, "goal");
		}
	}
}
