package com.hm.achievement.advancement;

/**
 * Class representing an advancement generated by Advanced Achievements.
 * 
 * @author Pyves
 *
 */
public class AchievementAdvancement {

	public static final String CRITERIA_NAME = "aach_handled";

	private final String iconItem;
	private final String iconData;
	private final String title;
	private final String description;
	private final String parent;
	private final String background;
	private final String frame;

	private AchievementAdvancement(String iconItem, String iconData, String title, String description, String parent,
			String background, String frame) {
		this.iconItem = iconItem;
		this.iconData = iconData;
		this.title = title;
		this.description = description;
		this.parent = parent;
		this.background = background;
		this.frame = frame;
	}

	public String getIconItem() {
		return iconItem;
	}

	public String getIconData() {
		return iconData;
	}

	public String getTitle() {
		return title;
	}

	public String getDescription() {
		return description;
	}

	public String getParent() {
		return parent;
	}

	public String getBackground() {
		return background;
	}

	public String getFrame() {
		return frame;
	}

	public static class AchievementAdvancementBuilder {

		private String iconItem;
		private String iconData;
		private String title;
		private String description;
		private String parent;
		private String background;
		private AdvancementType type;

		public AchievementAdvancementBuilder iconItem(String iconItem) {
			this.iconItem = iconItem;
			return this;
		}

		public AchievementAdvancementBuilder iconData(String iconData) {
			this.iconData = iconData;
			return this;
		}

		public AchievementAdvancementBuilder title(String title) {
			this.title = title;
			return this;
		}

		public AchievementAdvancementBuilder description(String description) {
			this.description = description;
			return this;
		}

		public AchievementAdvancementBuilder parent(String parent) {
			this.parent = parent;
			return this;
		}

		public AchievementAdvancementBuilder background(String background) {
			this.background = background;
			return this;
		}

		public AchievementAdvancementBuilder type(AdvancementType type) {
			this.type = type;
			return this;
		}

		public AchievementAdvancement build() {
			return new AchievementAdvancement(iconItem, iconData, title, description, parent, background, type.toString());
		}

	}
}
